# Generated by Django 5.0.1 on 2024-04-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
