# Generated by Django 5.0.1 on 2024-04-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_location_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='map_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
