# Generated by Django 5.0.1 on 2024-04-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='map_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
