# Generated by Django 5.0.1 on 2024-04-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_location_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='map_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
