# Generated by Django 5.0.1 on 2024-04-17 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_location_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='rating',
        ),
        migrations.AddField(
            model_name='location',
            name='cuisineID',
            field=models.ManyToManyField(to='restaurant.cuisine'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.location')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.location')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.location')),
            ],
        ),
        migrations.CreateModel(
            name='TagLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.location')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.tag')),
            ],
        ),
    ]
