# Generated by Django 5.0.1 on 2024-04-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_review_userloginid_cuisinelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CasualDining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happyhour', models.BooleanField()),
                ('outdoor_seating', models.BooleanField()),
                ('live_music', models.BooleanField()),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.location')),
            ],
        ),
        migrations.CreateModel(
            name='FineDining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_code', models.CharField(max_length=100)),
                ('michelin_star', models.IntegerField()),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.location')),
            ],
        ),
    ]
