# Generated by Django 5.0.1 on 2024-04-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
