# Generated by Django 5.0.1 on 2024-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_userlogin_is_active_userlogin_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
